### ISSUE TITLE
Unusual slowdown with 10 bit (hevc) output

### ISSUE THREAD

**Issue by BTMeeks** [lisamelton/other_video_transcoding#192]
Long time slow user of transcode and other-transcode, on MacOS, trying to get things working on Windows PC with Nvidia 3060.

My first three movies without hevc option were 175, 145, and 145 FPS. With the hevc option on the same 3 movies, I got 143, 6.2, and 127 fps. I'm trying to understand why that one title was 23x slower, not why the other two were a little slower.

I imagine this is more of an ffmpeg question, rather than other-transcode, but I thought I would start here. Log file attached.

[Bug report.zip](https://github.com/lisamelton/other_video_transcoding/files/12399585/Bug.report.zip)

**Comment by lisamelton** [comment]
@BTMeeks I'm sorry you're having this problem. Thank you for including `log` files. But the "8-Bit" folder seems to 10-bit data and the same as what's in the "10-bit" folder.

That said, I'm not seeing anything obvious as to why you're getting 6.2 FPS for _The Life Aquatic with Steve Zissou (2004)_.

**Comment by lisamelton** [comment]
@BTMeeks Also, as you suspected, this will most certainly be a FFmpeg issue.

**Comment by ttyS0** [comment]
@BTMeeks I notice you're running a git version of `ffmpeg`, (`2023-08-14-git-c704901324`). If there is a strange `ffmpeg` bug causing this, which it certainly has the smell of, you might want to try using the `5.1.2` release version, and see if the problem persists.

**Comment by BTMeeks** [comment]
@ttyS0 "That's a bingo". I swapped out my ffmpeg with 5.1.latest, and got 162 FPS on that title.  I didn't find 5.1.2, but 5.1.latest ended up being "ffmpeg version n5.1.3-16-g566aa38d98-20230826 ".

@lisamelton Yes, "most certainly be a FFmpeg issue".
