### ISSUE TITLE
batch.rb not transcoding

### ISSUE THREAD

**Issue by ramiltonii** [lisamelton/other_video_transcoding#204]
Hello & thanks for this great tool. I had been using this for a while on another computer & recently got a new computer. I was installing this & trying to re-create my process with the batch.rb. When i run a convert with other-transcode, it works fine. If i run the batch.rb it just skips down to the next line & doesn't convert anything. 

even when i put the batch.rb & queue.txt file in the same folder. 

Has anyone seen this before? 

![Screenshot 2024-05-18 224323](https://github.com/lisamelton/other_video_transcoding/assets/28348437/2e67c0f7-66ea-4ce2-ae9a-eaf37b28b751)

**Comment by lisamelton** [comment]
@ramiltonii You are very welcome and I'm sorry you're having this problem.

The `queue.txt` file actually needs to be in the current working directory for `batch.rb` to find it. Usually that means `batch.rb` is placed in that same directory. Is that where `batch.rb` is located?

**Comment by ramiltonii** [comment]
It is in the same directory. I actually added it in the /bin folder also. Put the file I want to convert in the same folder and everything. My old computer works fine, just the new install is acting weird! 😊 thanks for responding.

**Comment by lisamelton** [comment]
@ramiltonii Remove the `batch.rb` file from your `\bin` directory. Just execute it from the working directory, i.e. invoking it via `.\batch.rb`. That could be the problem.

**Comment by ramiltonii** [comment]
Thank you for responding to me. I was able to resolve. when i started trying to set up on my new machine, i started with other projects not seeing the other transcoding. They suggest to use WSL to install the tools. I re-read over your instructions & saw not to use the WSL. I uninstalled WSL & the batch.rb started working. Thanks for helping me!!!

**Comment by lisamelton** [comment]
@ramiltonii You are very welcome!

OK, I will close this now because the issue has been resolved.

**Comment by Kerbrer** [comment]
Can you explain what you did here? I think I have the same problem.

**Comment by lisamelton** [comment]
@Kerbrer Did you install `other-transcode.rb` in WSL? If so, don't use it in that environment. Use it within Windows itself via PowerShell.

**Comment by Kerbrer** [comment]
> @Kerbrer Did you install `other-transcode.rb` in WSL? If so, don't use it in that environment. Use it within Windows itself via PowerShell.

So I've made progress, now I get this error message:

C:/Ruby32-x64/bin/other-transcode: scanning media failed: [Path to file]\batch.rb

I've tried it both ways as such:
D:\Movies\bsgrip>other-transcode --add-audio all --add-subtitle all --copy-track-names [Path to file]\batch.rb
D:\Movies\bsgrip>other-transcode [Path to file]\batch.rb --add-audio all --add-subtitle all --copy-track-names

**Comment by lisamelton** [comment]
@Kerbrer OK, this is a separate problem. Can you open a new issue, please? I don't want to diagnose this in an issue that's already closed. Thanks.
