### ISSUE TITLE
line 8: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by ravedoglv** [lisamelton/other_video_transcoding#209]
Just reinstalled the latest version and tried running a command that worked up until this update and i get that error

Here is the command

`other-transcode --vt-allow-sw --mp4 ---deinterlace --crop 24:26:0:2 '/Users/ravedog/Desktop/rips/White Lightning (1973)/src/Gator Trailer.mkv'`

Any ideas?

**Comment by lisamelton** [comment]
@ravedoglv Sorry you're having this problem. But I have no idea what's going on. I assume you're on macOS? How did you install Ruby? And RubyGems? Normally issues like this are a failure of the Ruby runtime.

**Comment by loshlee** [comment]
Uh, too many hyphens before `deinterlace`?

**Comment by lisamelton** [comment]
@ravedoglv OK, what happens if you remove that extra hyphen/dash?

**Comment by ravedoglv** [comment]
> @ravedoglv OK, what happens if you remove that extra hyphen/dash?

duh. I don't know how that happen. However when i make it 2 dashes i still get the same error

**Comment by ravedoglv** [comment]
> @ravedoglv Sorry you're having this problem. But I have no idea what's going on. I assume you're on macOS? How did you install Ruby? And RubyGems? Normally issues like this are a failure of the Ruby runtime.

so i first uninstalled other transcode
then i brew upgrade
made sure my companion tools were up to date


then i ran `curl -Lo /usr/local/bin/other-transcode https://github.com/donmelton/other_video_transcoding/raw/master/bin/other-transcode
chmod a+x /usr/local/bin/other-transcode`

that's it.

Im on Mac OS 15.1

**Comment by skj-dev** [comment]
My guess is you're getting an HTML file instead of the Ruby script, as your URL isn't quite right. Try using `https://raw.githubusercontent.com/lisamelton/other_video_transcoding/refs/heads/master/other-transcode.rb` instead.

**Comment by ravedoglv** [comment]
> My guess is you're getting an HTML file instead of the Ruby script, as your URL isn't quite right. Try using `https://raw.githubusercontent.com/lisamelton/other_video_transcoding/refs/heads/master/other-transcode.rb` instead.

Forgive me but what do i do with that file?

**Comment by skj-dev** [comment]
Sorry, I thought you understood the rest of the command you were running. Here's the whole thing:

```
curl -Lo /usr/local/bin/other-transcode https://raw.githubusercontent.com/lisamelton/other_video_transcoding/refs/heads/master/other-transcode.rb && chmod a+x /usr/local/bin/other-transcode
```

**Comment by ravedoglv** [comment]
when i installed it originally it just installed the web page http because the url was wrong
i ran yours and it installed it properly
now im getting errors Requires `ffprobe`, `ffmpeg` and `mkvpropedit`.


which i installed using brew

**Comment by skj-dev** [comment]
I believe `brew install mkvtoolnix` is what you're after.

**Comment by ravedoglv** [comment]
All installed 

ran

`other-transcode  --mp4 -hevc --crop 20:20:0:0 --main-audio 1 --add-audio 1=stereo --add-audio 3 '/Users/ravedog/Desktop/rips/White Lightning (1973)/src/White Lightning (1973).mkv'`

I got 

`other-transcode  --mp4 -hevc --crop 20:20:0:0 --main-audio 1 --add-audio 1=stereo --add-audio 3 '/Users/ravedog/Desktop/rips/White Li
ghtning (1973)/src/White Lightning (1973).mkv'
Transcode Blu-ray Disc or DVD rip into a smaller, more portable format
while remaining high enough quality to be mistaken for the original.

Usage: other-transcode [OPTION]... [FILE]...

Creates Matroska `.mkv` format file in current working directory.

Automatically selects a platform-specific hardware video encoder.

Output options:
    --debug         increase diagnostic information
    --scan          print media information and exit
    --preview-crop  show commands to preview detected video crop and exit
-n, --dry-run       don't transcode, just show `ffmpeg` command and exit

Video options:
    --hevc          use HEVC version of platform-specific video encoder
    --target [2160p=|1080p=|720p=|480p=]BITRATE
                    set video bitrate target (default: based on input)
                      or target for specific input resolution
    --crop WIDTH:HEIGHT:X:Y|TOP:BOTTOM:LEFT:RIGHT|auto
                    set video crop geometry (default: none)
                      or automatically detect it
    --720p          fit video within 1280x720 pixel bounds

Audio options:
    --main-audio TRACK[=WIDTH]
                    select main audio track by number (default: 1)
                      with optional width (default: surround)
    --add-audio TRACK|all|LANGUAGE|STRING[=WIDTH]
                    add single audio track by number
                      including main audio track
                    or all audio tracks
                      excluding main audio track
                    or audio tracks by language code
                      excluding main audio track
                      (in ISO 639-2 format, e.g.: `eng`)
                    or audio tracks with titles containing string
                      excluding main audio track
                      (comparison is case-insensitve)
                    with optional width (default: stereo)
    --surround-bitrate BITRATE
                    set surround audio bitrate (default: 448)
    --stereo-bitrate BITRATE
                    set stereo audio bitrate (default: 128)
    --eac3          use Dolby Digital Plus (E-AC-3) format for all audio
                      (default bitrates: 448 for surround, 192 for stereo)

Subtitle options:
    --add-subtitle TRACK[=forced]|auto|all|LANGUAGE|STRING
                    add single subtitle track by number
                      optionally setting forced disposition
                    or enable automatic addition of forced subtitle
                    or add all subtitle tracks
                    or subtitle tracks by language code
                      (in ISO 639-2 format, e.g.: `eng`)
                    or subtitle tracks with titles containing string
                      (comparison is case-insensitve)
                    (variations exclude any burned track)
    --burn-subtitle TRACK|auto
                    burn subtitle track by number into video
                      or enable automatic burning of forced subtitle
                      (only image-based subtitles are burned)

Other options:
-h, --help [more|full]
                    display help and exit
                      optionally including more or full information
    --version       output version information and exit

Requires `ffprobe`, `ffmpeg` and `mkvpropedit`.`

**Comment by loshlee** [comment]
Maybe you still haven't met the dependencies.

I would investigate by using these three commands:
`which ffprobe`
`which ffmpeg`
`which mkvpropedit`

I get the following answers respectively (I have Silicon, if you have Intel, yours may reflect `/usr/local/bin` rather than `/opt/homebrew/bin`):
`/opt/homebrew/bin/ffprobe`
`/opt/homebrew/bin/ffmpeg`
`/opt/homebrew/bin/mkvpropedit`

If you see a valid path returned, you may have to check versions. If not, you may have to be sure the paths are correct for your environment. I'm not very good at providing succinct methods for a remedy, but I have developed a way to check the path environment that's makes them easy to read:

`echo "$PATH" | tr ':' '\n' | sort | uniq -c`

**Comment by skj-dev** [comment]
You have `-hevc`, but per the help it's supposed to be `--hevc`.

**Comment by ravedoglv** [comment]
I should not be allowed near a computer. the double dash was the trick.

I do have another question, but I'll open another issue. Thank you everyone.

So to recap:

- I installed other-transcode using an incorrect url
- I then was missing a dependency
- I then had an extra dash in a switch
- I then had only one dash on a switch.

Where's my head at?

THanks again.

**Comment by skj-dev** [comment]
`other-transcode` will attempt to discover if you have hardware encoder capabilities, and use them if discovered. If in the output you see `videotoolbox` mentioned (usually with the codec prefixed, like `h264_videotoolbox`), that means it's using Apple's hardware acceleration. QSV indicated Intel's hardware acceleration (via their embedded iGPU), and Nvidia is referenced as either nv-something or cuda maybe? It's been a long time since I've used Nvidia anything, so I don't exactly recall. 

The point is that hardware acceleration is attempted by default with this tool, and is you want software only that has to be specified as an option. :)

**Comment by ravedoglv** [comment]
that is awesome 

i get `Trying "hevc_videotoolbox" video encoder...`
`x265 [info]: HEVC encoder version 3.5+1-f0c1022b6`

so i noticed that if i used x265 (--hvec) that i get about 0.5X speed
if i remove that switch i get about 8X speed.

So encode x265 about 16X slower than h264?

**Comment by skj-dev** [comment]
It's sort of the other way around in a sense. `x264` is the absolute fastest, so everything else will look slow in comparison, often by orders of magnitude.

**Comment by skj-dev** [comment]
Unless you're tightly constrained with storage space, or you're dealing with HDR, there's nothing wrong with sticking to `x264`. At some point all this turns into chasing nuances of quality balanced by how much time one is willing to spend, and what kind of compatibility is needed. On that note, `x264` is also the most compatible, as it's been around the longest.

**Comment by ravedoglv** [comment]
thank you for that insight. Will use this going forward. Again, thank you to everyone.
